name: ci
on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Audit dependencies
      - run: npm audit
      - name: Lint project
      - run: npm run lint
      - name: Run unit and integration tests
      - run: npm test
